export const parentescos = [
    'ABUELO/A',
    'AMIGO_A',
    'CUIDADOR/A',
    'CUÑADO/A',
    'EMPLADO/A',
    'ENCARGADO/A',
    'ENFERMERO/A',
    'HERMANO/A',
    'HIJO/A',
    'MADRE SUSTITUTA',
    'MAMÁ',
    'MEDICO/A',
    'NIETO/A',
    'NUERA',
    'PADRE SUSTITUTO',
    'PAPÁ',
    'PAREJA',
    'PRIMO/A',
    'REGENTE',
    'SOBRINO/A',
    'SUEGRO/A',
    'TÍO/A',
    'TITULAR',
    'VECINO/A',
    'VIGILANTE',
    'YERNO',
]