export const parentescos = [
    { id: 'ABUELO_A', nombre: 'ABUELO/A' },
    { id: 'AMIGO_A', nombre: 'AMIGO/A' },
    { id: 'CUIDADOR_A', nombre: 'CUIDADOR/A' },
    { id: 'CUNADO_A', nombre: 'CUÑADO/A' },
    { id: 'EMPLADO_A', nombre: 'EMPLADO/A' },
    { id: 'ENCARGADO_A', nombre: 'ENCARGADO/A' },
    { id: 'ENFERMERO_A', nombre: 'ENFERMERO/A' },
    { id: 'HERMANO_A', nombre: 'HERMANO/A' },
    { id: 'HIJO_A', nombre: 'HIJO/A' },
    { id: 'MADRE_SUSTITUTA', nombre: 'MADRE SUSTITUTA' },
    { id: 'MAMA', nombre: 'MAMÁ' },
    { id: 'MEDICO_A', nombre: 'MEDICO/A' },
    { id: 'NIETO_A', nombre: 'NIETO/A' },
    { id: 'NUERA', nombre: 'NUERA' },
    { id: 'PADRE_SUSTITUTO', nombre: 'PADRE SUSTITUTO' },
    { id: 'PAPA', nombre: 'PAPÁ' },
    { id: 'PAREJA', nombre: 'PAREJA' },
    { id: 'PRIMO_A', nombre: 'PRIMO/A' },
    { id: 'REGENTE', nombre: 'REGENTE' },
    { id: 'SOBRINO_A', nombre: 'SOBRINO/A' },
    { id: 'SUEGRO_A', nombre: 'SUEGRO/A' },
    { id: 'TIO_A', nombre: 'TÍO/A' },
    { id: 'TITULAR', nombre: 'TITULAR' },
    { id: 'VECINO_A', nombre: 'VECINO/A' },
    { id: 'VIGILANTE', nombre: 'VIGILANTE' },
    { id: 'YERNO', nombre: 'YERNO' }
];